data:
  batch_size: 4
  color_jitter_strength: 0.0
  crop_scale:
  - 0.3
  - 1.0
  crop_size: 126
  image_folder: ../../../../../global/cfs/cdirs/m4392/ACAT_Backup/Data/Top/Boosted_Top.h5
  num_workers: 2
  pin_mem: true
  root_path: ../../../../../global/cfs/cdirs/m4392/ACAT_Backup/Data/Top/Boosted_Top.h5
  use_color_distortion: false
  use_gaussian_blur: false
  use_horizontal_flip: false
  split_size: 75
  chunk_size: 32
logging:
  folder: /pscratch/sd/t/tripodi/Logging
  write_tag: ijepa_gsoc
mask:
  allow_overlap: false
  aspect_ratio:
  - 0.75
  - 1.5
  enc_mask_scale:
  - 0.85
  - 1.0
  min_keep: 10
  num_enc_masks: 1
  num_pred_masks: 4
  patch_size: 9
  pred_mask_scale:
  - 0.15
  - 0.2
meta:
  copy_data: false
  load_checkpoint: false
  model_name: vit_base
  pred_depth: 12
  pred_emb_dim: 384
  read_checkpoint: null
  use_bfloat16: true
optimization:
  scheduler: cosine
  ema:
  - 0.996
  - 1.0
  epochs: 20
  final_lr: 1.0e-06
  final_weight_decay: 0.4
  ipe_scale: 1.0
  lr: 0.0001
  start_lr: 0.00001
  warmup: 1
  weight_decay: 0.04
