data:
  batch_size: 8
  chunk_size: 32
  img_size: 126
  patch_size: 14
  num_classes: 1
  num_workers: 2
  pin_mem: true
  root_path: /Data/Dataset_normalized.h5
logging:
  folder: /Logging/vit_base
  write_tag: probing_ijepa
meta:
  model_name: vit_base
  pretrained_path: /Logging/epoch.tz
  use_batch_norm: false
optimization:
  num_epochs: 50
  start_lr: 0.0002
  final_lr: 1.0e-06
