data:
  batch_size: 8
  chunk_size: 32
  img_size: 126
  patch_size: 9
  num_classes: 1
  num_workers: 2
  pin_mem: true
  root_path: ../../../../../global/cfs/cdirs/m4392/ACAT_Backup/Data/Top/Boosted_Top.h5
logging:
  folder: /pscratch/sd/t/tripodi/Logging/resnet50
  write_tag: probing_ijepa
meta:
  model_name: resnet_50
  pretrained_path: null
  use_batch_norm: false
optimization:
  num_epochs: 40
  start_lr: 0.001
  final_lr: 1.0e-06
