data:
  batch_size: 8
  chunk_size: 32
  img_size: 126
  patch_size: 7
  num_classes: 1
  num_workers: 2
  pin_mem: true
  root_path: ../../../../../global/cfs/cdirs/m4392/ACAT_Backup/Data/Top/Boosted_Top.h5
logging:
  folder: /pscratch/sd/t/tripodi/Logging/vit_s_7_75_iris
  write_tag: probing_ijepa
meta:
  model_name: vit_small
  pretrained_path: /pscratch/sd/t/tripodi/Logging/vit_s_7_75_iris/ijepa_gsoc-ep9.pth.tar
  use_batch_norm: false
optimization:
  num_epochs: 40
  start_lr: 0.001
  final_lr: 1.0e-06
